version: '3.8'

services:
  petclinic-db:
    image: mysql:8.0
    container_name: petclinic-mysql-prod
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=petclinic
    volumes:
      - mysql_production_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  petclinic-app:
    # Sau khi Jenkins build xong sẽ đẩy lên Docker Hub của bạn, ví dụ:_ten_tai_khoan/spring-petclinic:latest
    image: ${DOCKER_HUB_USER}/spring-petclinic:latest
    container_name: petclinic-app-prod
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=mysql
      - SPRING_DATASOURCE_URL=jdbc:mysql://petclinic-db:3306/petclinic?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      petclinic-db:
        condition: service_healthy

volumes:
  mysql_production_data: